tmux kill-session -t accidents
tmux kill-session -t ad
tmux kill-session -t bbc
tmux kill-session -t baudio
tmux kill-session -t bnetflix
tmux kill-session -t cr52
tmux kill-session -t c20ng
tmux kill-session -t dna
tmux kill-session -t book
tmux kill-session -t cwebkb
tmux kill-session -t jester
tmux kill-session -t kdd
tmux kill-session -t kosarek
tmux kill-session -t msnbc
tmux kill-session -t msweb
tmux kill-session -t nltcs
tmux kill-session -t plants
tmux kill-session -t pumsb_star
tmux kill-session -t tmovie
tmux kill-session -t tretail

